const sgMail = require('@sendgrid/mail')

const forgotPassword = (email, password) => {
    //sgMail.setApiKey(process.env.SENDGRID_API_KEY)
    console.log('temporary password: ' + password);
    sgMail.setApiKey("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");
    //sgMail.setApiKey("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")
    const msg = {
        to: email, // Change to your recipient
        from: 'info@synnovate.ca', // Change to your verified sender
        subject: 'Password Forget Request sent for sVAQ App',
        text: 'This is an autogenerated email for your invoice.',
        html: '<strong>You have requested for password forget.</strong><br/>Your new password is <strong>' + password + '<strong>.<br/><br/>If you have not requested this please let us know.',
    }
    sgMail
        .send(msg)
        .then(() => {
            console.log('Email sent for forgot pass.')
        })
        .catch((error) => {
            console.error(error)
        })
}

module.exports = forgotPassword